# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QmiqH5gmxd0UQBifsfyHu5oEvk0sB5l4
"""

import pandas as pd

bankfull = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/bank-full2.xlsx")

bankfull.head(n=30)

print(bankfull.shape)

bankfull.isnull().any().any()

video = bankfull.dropna(axis=0)

print(bankfull.shape)

banksimple = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/banksimple.xlsx")

banksimple.head(n=30)

print(banksimple.shape)

bankfull.isnull().any().any()

video = banksimple.dropna(axis=0)
print(banksimple.shape)

filter1 = bankfull['job'] != 'unemployed'

print(bankfull[filter1].shape)

bankfull[filter1].head(n=30)

import numpy as np

bankfull['abletoapply'] = np.where (
    bankfull['poutcome'] != 'failure',
    'yes',
    'no'
)

bankfull.head(n=26792)

bankfull[filter1].head(n=26792)

print(bankfull[filter1].shape)

bankfull.groupby(['education', 'age', 'job']).sum()

import plotly.express as px
px.histogram(bankfull, x = 'age')

import matplotlib.pyplot as plt
bankfull.plot.scatter('duration', 'age')